---
- hosts: localhost
  connection: local
  tasks:

    - name: "present the state"
      terraform:
        state: present
        project_path: "{{ playbook_dir }}/terraform_modules/module_tc_3_0_var_string"
        force_init: true
        variables:
          variable_string: "sample content"


    - name: "absent the state"
      terraform:
        state: absent
        project_path: "{{ playbook_dir }}/terraform_modules/module_tc_3_0_var_string"
        variables:
          variable_string: "sample content"
