---
- hosts: localhost
  connection: local
  tasks:

    - name: "present the state"
      terraform:
        state: present
        project_path: "{{ playbook_dir }}/terraform_modules/module_tc_3_2_var_list"
        force_init: true
        variables:
          variable_list:
            - "test 1"
            - "test 2"


    - name: "absent the state"
      terraform:
        state: absent
        project_path: "{{ playbook_dir }}/terraform_modules/module_tc_3_2_var_list"
        variables:
          variable_list:
            - "test 1"
            - "test 2"
