---
- hosts: localhost
  connection: local
  tasks:

    - name: "present the state"
      terraform:
        state: present
        project_path: "{{ playbook_dir }}/terraform_modules/module_tc_3_3_var_map"
        force_init: true
        variables:
          variable_map:
            content: "test content"
            second: "other Value"


    - name: "absent the state"
      terraform:
        state: absent
        project_path: "{{ playbook_dir }}/terraform_modules/module_tc_3_3_var_map"
        variables:
          variable_map:
            content: "test content"
            second: "other Value"
