---
- hosts: localhost
  connection: local
  tasks:

    - name: "present the state"
      terraform:
        state: present
        project_path: "{{ playbook_dir }}/terraform_modules/module_tc_0_0_no_config"
        state_file: "{{ terraform_state_file }}"
        force_init: true


    - name: "absent the state"
      terraform:
        state: absent
        project_path: "{{ playbook_dir }}/terraform_modules/module_tc_0_0_no_config"
        state_file: "{{ terraform_state_file }}"
