---
- hosts: localhost
  connection: local
  tasks:

    - set_fact:
        test_create_file: "{{ playbook_dir }}/test_module_output/ansible_only_state_file.txt"
        state_target_file: "{{ state_target }}/terraform.tfstate"

    - name: "present the state"
      terraform:
        state: present
        project_path: "{{ playbook_dir }}/terraform_modules/example_module"
        state_file: "{{ state_target_file }}"
        variables:
          target_name: "{{ test_create_file }}"
#
    - name: "absent the state"
      terraform:
        state: absent
        project_path: "{{ playbook_dir }}/terraform_modules/example_module"
        state_file: "{{ state_target_file }}"
        variables:
          target_name: "{{ test_create_file }}"
